services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
#    depends_on:
#      - frontend

#  frontend:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile.frontend
#    ports:
#      - "3000:80"
